import type { ThemeId } from "./themes";

export type ResolvedAppearance = "light" | "dark";

export type ThemeColorTokens = {
  background: string;
  foreground: string;
  foregroundMuted: string;
  accent: string;
  accentSoft: string;
  accentAlt: string;
  surface: string;
  surfaceElevated: string;
  surfaceCard: string;
  surfaceCardAlt: string;
  border: string;
  borderMuted: string;
  danger: string;
  dangerSurface: string;
  btnPrimaryBg: string;
  btnPrimaryText: string;
  btnPrimaryBorder: string;
  btnSecondaryBg: string;
  btnSecondaryText: string;
  btnSecondaryBorder: string;
  textOnCard: string;
  cardRed: string;
  cardBlack: string;
  dangerText: string;
  borderWeight: number;
  radiusPanel: number;
  radiusBtn: number;
  radiusCard: number;
};

export type ThemeTokenSet = Record<ResolvedAppearance, ThemeColorTokens>;

export const THEME_COLOR_TOKENS: Record<ThemeId, ThemeTokenSet> = {
  "retro": {
    "dark": {
      "background": "#12061f",
      "foreground": "#00f5ff",
      "foregroundMuted": "#6dd4d8",
      "accent": "#ff00aa",
      "accentSoft": "#ff6ec7",
      "accentAlt": "#00f5ff",
      "surface": "rgba(18, 6, 31, 0.88)",
      "surfaceElevated": "rgba(45, 27, 105, 0.55)",
      "surfaceCard": "#2d1b69",
      "surfaceCardAlt": "#1a0a2e",
      "border": "#00f5ff",
      "borderMuted": "rgba(0, 245, 255, 0.45)",
      "danger": "#ff00aa",
      "dangerSurface": "#4a0e2e",
      "btnPrimaryBg": "#ff00aa",
      "btnPrimaryText": "#12061f",
      "btnPrimaryBorder": "#ff6ec7",
      "btnSecondaryBg": "#2d1b69",
      "btnSecondaryText": "#00f5ff",
      "btnSecondaryBorder": "#00f5ff",
      "textOnCard": "#9efbff",
      "cardRed": "#ff8ecf",
      "cardBlack": "#7ef9ff",
      "dangerText": "#ffb8e0",
      "borderWeight": 4,
      "radiusPanel": 0,
      "radiusBtn": 0,
      "radiusCard": 0
    },
    "light": {
      "background": "#f5efff",
      "foreground": "#3a1d5f",
      "foregroundMuted": "#6b5491",
      "accent": "#cc0087",
      "accentSoft": "#e056ad",
      "accentAlt": "#007f91",
      "surface": "rgba(252, 248, 255, 0.92)",
      "surfaceElevated": "rgba(238, 226, 255, 0.9)",
      "surfaceCard": "#e3d2ff",
      "surfaceCardAlt": "#f5ecff",
      "border": "#8f5ac5",
      "borderMuted": "rgba(143, 90, 197, 0.36)",
      "danger": "#c2185b",
      "dangerSurface": "#ffe2ee",
      "btnPrimaryBg": "#d81b93",
      "btnPrimaryText": "#fff8ff",
      "btnPrimaryBorder": "#f48dcb",
      "btnSecondaryBg": "#e8daff",
      "btnSecondaryText": "#3a1d5f",
      "btnSecondaryBorder": "#b999ea",
      "textOnCard": "#3a1d5f",
      "cardRed": "#bf267e",
      "cardBlack": "#2f5f72",
      "dangerText": "#8d1c4f",
      "borderWeight": 4,
      "radiusPanel": 0,
      "radiusBtn": 0,
      "radiusCard": 0
    }
  },
  "casino": {
    "dark": {
      "background": "#0a1f12",
      "foreground": "#f5e6c8",
      "foregroundMuted": "#c4b59a",
      "accent": "#d4af37",
      "accentSoft": "#e8c96a",
      "accentAlt": "#d4edd4",
      "surface": "rgba(12, 36, 22, 0.94)",
      "surfaceElevated": "rgba(22, 58, 36, 0.72)",
      "surfaceCard": "#163a24",
      "surfaceCardAlt": "#0f2818",
      "border": "#d4af37",
      "borderMuted": "rgba(212, 175, 55, 0.4)",
      "danger": "#c94c4c",
      "dangerSurface": "#3d1f1f",
      "btnPrimaryBg": "#c9a227",
      "btnPrimaryText": "#0a1f12",
      "btnPrimaryBorder": "#f5e6c8",
      "btnSecondaryBg": "#163a24",
      "btnSecondaryText": "#f5e6c8",
      "btnSecondaryBorder": "#8fbc8f",
      "textOnCard": "#f5ebe0",
      "cardRed": "#f0c878",
      "cardBlack": "#d8f0d8",
      "dangerText": "#ffd4d4",
      "borderWeight": 2,
      "radiusPanel": 8,
      "radiusBtn": 6,
      "radiusCard": 4
    },
    "light": {
      "background": "#f6f2e8",
      "foreground": "#2d2a22",
      "foregroundMuted": "#655f52",
      "accent": "#a87f25",
      "accentSoft": "#bf9640",
      "accentAlt": "#35674d",
      "surface": "rgba(255, 251, 242, 0.94)",
      "surfaceElevated": "rgba(246, 237, 221, 0.9)",
      "surfaceCard": "#ece2cf",
      "surfaceCardAlt": "#f8f2e4",
      "border": "#b38a31",
      "borderMuted": "rgba(179, 138, 49, 0.35)",
      "danger": "#b84a4a",
      "dangerSurface": "#f9e7e3",
      "btnPrimaryBg": "#c09838",
      "btnPrimaryText": "#241d14",
      "btnPrimaryBorder": "#f7ecd4",
      "btnSecondaryBg": "#ece2cf",
      "btnSecondaryText": "#2d2a22",
      "btnSecondaryBorder": "#c2b49a",
      "textOnCard": "#2d2a22",
      "cardRed": "#b46b3b",
      "cardBlack": "#345540",
      "dangerText": "#7f2c2c",
      "borderWeight": 2,
      "radiusPanel": 8,
      "radiusBtn": 6,
      "radiusCard": 4
    }
  },
  "party": {
    "dark": {
      "background": "#1a0a3e",
      "foreground": "#fff5a0",
      "foregroundMuted": "#e8dc90",
      "accent": "#ff4fd8",
      "accentSoft": "#ff9ae8",
      "accentAlt": "#b8f8ff",
      "surface": "rgba(26, 10, 62, 0.82)",
      "surfaceElevated": "rgba(120, 50, 180, 0.45)",
      "surfaceCard": "#6b3fa8",
      "surfaceCardAlt": "#3d2078",
      "border": "#ff4fd8",
      "borderMuted": "rgba(255, 79, 216, 0.5)",
      "danger": "#ff3366",
      "dangerSurface": "#6a1a4a",
      "btnPrimaryBg": "#ff6b9d",
      "btnPrimaryText": "#1a0a3e",
      "btnPrimaryBorder": "#fff5a0",
      "btnSecondaryBg": "#4a2d8a",
      "btnSecondaryText": "#c8f8ff",
      "btnSecondaryBorder": "#6ee7ff",
      "textOnCard": "#fff8c8",
      "cardRed": "#ffc8f0",
      "cardBlack": "#c8f8ff",
      "dangerText": "#ffd0e8",
      "borderWeight": 3,
      "radiusPanel": 20,
      "radiusBtn": 9999,
      "radiusCard": 12
    },
    "light": {
      "background": "#fff1fb",
      "foreground": "#3c1c54",
      "foregroundMuted": "#755888",
      "accent": "#cf2fae",
      "accentSoft": "#ea6dd2",
      "accentAlt": "#1f7f8f",
      "surface": "rgba(255, 248, 255, 0.9)",
      "surfaceElevated": "rgba(244, 227, 255, 0.86)",
      "surfaceCard": "#efd6ff",
      "surfaceCardAlt": "#fff1fb",
      "border": "#d84eb9",
      "borderMuted": "rgba(216, 78, 185, 0.34)",
      "danger": "#d93566",
      "dangerSurface": "#ffe0ef",
      "btnPrimaryBg": "#ff86b6",
      "btnPrimaryText": "#3c1c54",
      "btnPrimaryBorder": "#ffe6f7",
      "btnSecondaryBg": "#efd6ff",
      "btnSecondaryText": "#3c1c54",
      "btnSecondaryBorder": "#cfa6ec",
      "textOnCard": "#3c1c54",
      "cardRed": "#c43c96",
      "cardBlack": "#2c6f86",
      "dangerText": "#94274e",
      "borderWeight": 3,
      "radiusPanel": 20,
      "radiusBtn": 9999,
      "radiusCard": 12
    }
  },
  "minimal": {
    "dark": {
      "background": "#0c0c10",
      "foreground": "#e4e6eb",
      "foregroundMuted": "#a0a8b4",
      "accent": "#2dd4bf",
      "accentSoft": "#5eead4",
      "accentAlt": "#b8c0cc",
      "surface": "rgba(14, 14, 18, 0.92)",
      "surfaceElevated": "rgba(22, 22, 30, 0.85)",
      "surfaceCard": "#1a1a24",
      "surfaceCardAlt": "#0c0c10",
      "border": "#2dd4bf",
      "borderMuted": "rgba(45, 212, 191, 0.22)",
      "danger": "#f472b6",
      "dangerSurface": "#1e1a22",
      "btnPrimaryBg": "#2dd4bf",
      "btnPrimaryText": "#0c0c10",
      "btnPrimaryBorder": "#5eead4",
      "btnSecondaryBg": "#1a1a24",
      "btnSecondaryText": "#e4e6eb",
      "btnSecondaryBorder": "#3a3a48",
      "textOnCard": "#d8dce2",
      "cardRed": "#7ee8d8",
      "cardBlack": "#c4cad4",
      "dangerText": "#f8a8c8",
      "borderWeight": 1,
      "radiusPanel": 6,
      "radiusBtn": 4,
      "radiusCard": 4
    },
    "light": {
      "background": "#f5f7fa",
      "foreground": "#111827",
      "foregroundMuted": "#4b5563",
      "accent": "#0f766e",
      "accentSoft": "#0d9488",
      "accentAlt": "#6b7280",
      "surface": "rgba(255, 255, 255, 0.92)",
      "surfaceElevated": "rgba(248, 250, 252, 0.95)",
      "surfaceCard": "#e5e7eb",
      "surfaceCardAlt": "#f8fafc",
      "border": "#0f766e",
      "borderMuted": "rgba(15, 118, 110, 0.24)",
      "danger": "#be185d",
      "dangerSurface": "#fde7f1",
      "btnPrimaryBg": "#0f766e",
      "btnPrimaryText": "#f8fafc",
      "btnPrimaryBorder": "#14b8a6",
      "btnSecondaryBg": "#e5e7eb",
      "btnSecondaryText": "#111827",
      "btnSecondaryBorder": "#cbd5e1",
      "textOnCard": "#111827",
      "cardRed": "#0f766e",
      "cardBlack": "#374151",
      "dangerText": "#9d174d",
      "borderWeight": 1,
      "radiusPanel": 6,
      "radiusBtn": 4,
      "radiusCard": 4
    }
  },
  "calm": {
    "dark": {
      "background": "#17221c",
      "foreground": "#e6e3dc",
      "foregroundMuted": "#a8b2a9",
      "accent": "#c98f96",
      "accentSoft": "#d9a9af",
      "accentAlt": "#90b39c",
      "surface": "rgba(20, 31, 26, 0.9)",
      "surfaceElevated": "rgba(33, 48, 40, 0.84)",
      "surfaceCard": "#2a3a32",
      "surfaceCardAlt": "#1d2b24",
      "border": "#6f8a78",
      "borderMuted": "rgba(143, 179, 156, 0.3)",
      "danger": "#d28a94",
      "dangerSurface": "#472a31",
      "btnPrimaryBg": "#7d9b8a",
      "btnPrimaryText": "#0f1914",
      "btnPrimaryBorder": "#9bb5a4",
      "btnSecondaryBg": "#2a3a32",
      "btnSecondaryText": "#e6e3dc",
      "btnSecondaryBorder": "#6f8a78",
      "textOnCard": "#e6e3dc",
      "cardRed": "#d7a0a7",
      "cardBlack": "#c3cec5",
      "dangerText": "#f2c8ce",
      "borderWeight": 1,
      "radiusPanel": 16,
      "radiusBtn": 12,
      "radiusCard": 10
    },
    "light": {
      "background": "#f4f0ea",
      "foreground": "#243028",
      "foregroundMuted": "#516256",
      "accent": "#8b4a52",
      "accentSoft": "#7a4048",
      "accentAlt": "#3d5748",
      "surface": "rgba(255, 252, 248, 0.92)",
      "surfaceElevated": "rgba(237, 232, 224, 0.95)",
      "surfaceCard": "#e8e2d8",
      "surfaceCardAlt": "#f0ebe3",
      "border": "#b8c9bb",
      "borderMuted": "rgba(125, 155, 138, 0.35)",
      "danger": "#c97b84",
      "dangerSurface": "#f8ecee",
      "btnPrimaryBg": "#7d9b8a",
      "btnPrimaryText": "#f8f6f3",
      "btnPrimaryBorder": "#9bb5a4",
      "btnSecondaryBg": "#ede8e0",
      "btnSecondaryText": "#3d4f44",
      "btnSecondaryBorder": "#c9d4cb",
      "textOnCard": "#243028",
      "cardRed": "#8b4a52",
      "cardBlack": "#2a3830",
      "dangerText": "#7a3040",
      "borderWeight": 1,
      "radiusPanel": 16,
      "radiusBtn": 12,
      "radiusCard": 10
    }
  },
  "library": {
    "dark": {
      "background": "#1c1410",
      "foreground": "#f0e6d6",
      "foregroundMuted": "#a89880",
      "accent": "#c9a55c",
      "accentSoft": "#dcc88a",
      "accentAlt": "#8b4a52",
      "surface": "rgba(28, 20, 16, 0.94)",
      "surfaceElevated": "rgba(42, 30, 22, 0.88)",
      "surfaceCard": "#2d2218",
      "surfaceCardAlt": "#1a120c",
      "border": "#c9a55c",
      "borderMuted": "rgba(201, 165, 92, 0.32)",
      "danger": "#a84848",
      "dangerSurface": "#3a2020",
      "btnPrimaryBg": "#c9a55c",
      "btnPrimaryText": "#1c1410",
      "btnPrimaryBorder": "#f0e6d6",
      "btnSecondaryBg": "#2d2218",
      "btnSecondaryText": "#f0e6d6",
      "btnSecondaryBorder": "#6b5040",
      "textOnCard": "#e8dcc8",
      "cardRed": "#d4a878",
      "cardBlack": "#c8b8a8",
      "dangerText": "#e8b8b8",
      "borderWeight": 2,
      "radiusPanel": 8,
      "radiusBtn": 6,
      "radiusCard": 6
    },
    "light": {
      "background": "#f6efe2",
      "foreground": "#2b2118",
      "foregroundMuted": "#6a5a48",
      "accent": "#9a7234",
      "accentSoft": "#b3884b",
      "accentAlt": "#7a4950",
      "surface": "rgba(255, 250, 242, 0.92)",
      "surfaceElevated": "rgba(244, 234, 220, 0.88)",
      "surfaceCard": "#ebdfcd",
      "surfaceCardAlt": "#f6efe2",
      "border": "#b08a4c",
      "borderMuted": "rgba(176, 138, 76, 0.32)",
      "danger": "#a14b4b",
      "dangerSurface": "#f6e3de",
      "btnPrimaryBg": "#b99250",
      "btnPrimaryText": "#2b2118",
      "btnPrimaryBorder": "#f8e9d0",
      "btnSecondaryBg": "#ebdfcd",
      "btnSecondaryText": "#2b2118",
      "btnSecondaryBorder": "#bda58c",
      "textOnCard": "#2b2118",
      "cardRed": "#9e5f43",
      "cardBlack": "#4e4338",
      "dangerText": "#7f3535",
      "borderWeight": 2,
      "radiusPanel": 8,
      "radiusBtn": 6,
      "radiusCard": 6
    }
  },
  "lodge": {
    "dark": {
      "background": "#0f1a14",
      "foreground": "#f5e8d0",
      "foregroundMuted": "#a8b098",
      "accent": "#e8a045",
      "accentSoft": "#f0c060",
      "accentAlt": "#5a8a68",
      "surface": "rgba(15, 26, 20, 0.92)",
      "surfaceElevated": "rgba(22, 38, 30, 0.85)",
      "surfaceCard": "#1e3328",
      "surfaceCardAlt": "#122018",
      "border": "#8a6840",
      "borderMuted": "rgba(138, 104, 64, 0.4)",
      "danger": "#c06040",
      "dangerSurface": "#3a2018",
      "btnPrimaryBg": "#e8a045",
      "btnPrimaryText": "#0f1a14",
      "btnPrimaryBorder": "#f5e8d0",
      "btnSecondaryBg": "#1e3328",
      "btnSecondaryText": "#f5e8d0",
      "btnSecondaryBorder": "#5a8a68",
      "textOnCard": "#e8dcc0",
      "cardRed": "#f0c080",
      "cardBlack": "#b8d0c0",
      "dangerText": "#f0c8b0",
      "borderWeight": 2,
      "radiusPanel": 12,
      "radiusBtn": 10,
      "radiusCard": 8
    },
    "light": {
      "background": "#f2ede3",
      "foreground": "#2e2b22",
      "foregroundMuted": "#615b4e",
      "accent": "#b6782f",
      "accentSoft": "#cc8e42",
      "accentAlt": "#4f6f5b",
      "surface": "rgba(252, 248, 240, 0.92)",
      "surfaceElevated": "rgba(242, 233, 220, 0.9)",
      "surfaceCard": "#e6dccd",
      "surfaceCardAlt": "#f2ede3",
      "border": "#9c7b4d",
      "borderMuted": "rgba(156, 123, 77, 0.34)",
      "danger": "#a45b3f",
      "dangerSurface": "#f8e7df",
      "btnPrimaryBg": "#be863f",
      "btnPrimaryText": "#2e2b22",
      "btnPrimaryBorder": "#f6e8cf",
      "btnSecondaryBg": "#e6dccd",
      "btnSecondaryText": "#2e2b22",
      "btnSecondaryBorder": "#b9a387",
      "textOnCard": "#2e2b22",
      "cardRed": "#a45b3f",
      "cardBlack": "#3e5446",
      "dangerText": "#7b3d2c",
      "borderWeight": 2,
      "radiusPanel": 12,
      "radiusBtn": 10,
      "radiusCard": 8
    }
  },
  "ink": {
    "dark": {
      "background": "#141414",
      "foreground": "#f2ece2",
      "foregroundMuted": "#aea79d",
      "accent": "#d96a5b",
      "accentSoft": "#e58a7d",
      "accentAlt": "#d6d0c8",
      "surface": "rgba(18, 18, 18, 0.94)",
      "surfaceElevated": "rgba(28, 28, 28, 0.9)",
      "surfaceCard": "#26211d",
      "surfaceCardAlt": "#1a1714",
      "border": "#756c63",
      "borderMuted": "rgba(214, 208, 200, 0.22)",
      "danger": "#d96a5b",
      "dangerSurface": "#4a2723",
      "btnPrimaryBg": "#d96a5b",
      "btnPrimaryText": "#1a1714",
      "btnPrimaryBorder": "#e58a7d",
      "btnSecondaryBg": "#26211d",
      "btnSecondaryText": "#f2ece2",
      "btnSecondaryBorder": "#756c63",
      "textOnCard": "#f2ece2",
      "cardRed": "#e58a7d",
      "cardBlack": "#d6d0c8",
      "dangerText": "#f4c1b8",
      "borderWeight": 1,
      "radiusPanel": 2,
      "radiusBtn": 2,
      "radiusCard": 2
    },
    "light": {
      "background": "#f5f0e8",
      "foreground": "#1a1a1a",
      "foregroundMuted": "#5a5a5a",
      "accent": "#c23c2a",
      "accentSoft": "#d85548",
      "accentAlt": "#2a2a2a",
      "surface": "rgba(252, 248, 242, 0.95)",
      "surfaceElevated": "rgba(245, 238, 228, 0.98)",
      "surfaceCard": "#ebe4d8",
      "surfaceCardAlt": "#f5f0e8",
      "border": "#8a8078",
      "borderMuted": "rgba(42, 42, 42, 0.18)",
      "danger": "#c23c2a",
      "dangerSurface": "#f8ece8",
      "btnPrimaryBg": "#c23c2a",
      "btnPrimaryText": "#f5f0e8",
      "btnPrimaryBorder": "#d85548",
      "btnSecondaryBg": "#ebe4d8",
      "btnSecondaryText": "#1a1a1a",
      "btnSecondaryBorder": "#b8b0a8",
      "textOnCard": "#1a1a1a",
      "cardRed": "#c23c2a",
      "cardBlack": "#2a2a2a",
      "dangerText": "#8b2020",
      "borderWeight": 1,
      "radiusPanel": 2,
      "radiusBtn": 2,
      "radiusCard": 2
    }
  }
} as const;

export function getThemeColorTokens(theme: ThemeId, appearance: ResolvedAppearance): ThemeColorTokens {
  return THEME_COLOR_TOKENS[theme][appearance];
}

export function themeTokensToNativeWindVars(tokens: ThemeColorTokens): Record<string, string | number> {
  return {
    "--color-background": tokens.background,
    "--color-foreground": tokens.foreground,
    "--color-foreground-muted": tokens.foregroundMuted,
    "--color-accent": tokens.accent,
    "--color-accent-soft": tokens.accentSoft,
    "--color-accent-alt": tokens.accentAlt,
    "--color-surface": tokens.surface,
    "--color-surface-elevated": tokens.surfaceElevated,
    "--color-surface-card": tokens.surfaceCard,
    "--color-surface-card-alt": tokens.surfaceCardAlt,
    "--color-border": tokens.border,
    "--color-border-muted": tokens.borderMuted,
    "--color-danger": tokens.danger,
    "--color-danger-surface": tokens.dangerSurface,
    "--color-btn-primary-bg": tokens.btnPrimaryBg,
    "--color-btn-primary-text": tokens.btnPrimaryText,
    "--color-btn-primary-border": tokens.btnPrimaryBorder,
    "--color-btn-secondary-bg": tokens.btnSecondaryBg,
    "--color-btn-secondary-text": tokens.btnSecondaryText,
    "--color-btn-secondary-border": tokens.btnSecondaryBorder,
    "--color-text-on-card": tokens.textOnCard,
    "--radius-panel": tokens.radiusPanel,
    "--radius-btn": tokens.radiusBtn,
    "--radius-card": tokens.radiusCard,
    "--border-weight": tokens.borderWeight,
  };
}

