name = "cambio"
main = "party/worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "Main"
class_name = "CambioParty"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CambioParty"]
